# Dependencies
##markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ysjin.github.io
tagline:          '진용석의 블로그'
description:      ysjin's blog
url:              http://ysjin.github.io

author:
  name:           Yongseok Jin
  email:          yongseok.jin@gmail.com
#  url:            https://twitter.com/mdo

paginate:         3

# Custom vars
version:          1.0

#github:
#  repo:           https://github.com/

#pages_list:
#  About: '/about'
#  Archive: '/archive'
